import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Link } from "react-router-dom";
import { Sparkles, ArrowRight, Loader2, Globe } from "lucide-react";
import { collection, query, orderBy, limit, getDocs } from "firebase/firestore";
import { db } from "../lib/firebase";

export function Gallery() {
  const [designs, setDesigns] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDesigns = async () => {
      try {
        const q = query(collection(db, "designs"), orderBy("createdAt", "desc"), limit(12));
        const querySnapshot = await getDocs(q);
        const fetched = querySnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
        setDesigns(fetched);
      } catch (err) {
        console.error("Error fetching gallery:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchDesigns();
  }, []);

  return (
    <div className="space-y-12">
      <div className="text-center md:text-left">
        <h1 className="text-4xl font-bold tracking-tight mb-4">Design Gallery</h1>
        <p className="text-[#A1A1AA] max-w-2xl">
          Browse design systems generated by the community. See how AI interprets different visual languages.
        </p>
      </div>

      <AnimatePresence mode="wait">
        {loading ? (
          <div className="flex flex-col items-center py-20">
            <Loader2 className="w-10 h-10 text-teal-500 animate-spin" />
            <p className="mt-4 text-[#52525B] font-mono text-xs uppercase tracking-widest">Loading Repository...</p>
          </div>
        ) : designs.length > 0 ? (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
          >
            {designs.map((design) => (
              <Link 
                key={design.id}
                to={`/result/${design.id}`}
                className="group relative p-8 rounded-[32px] bg-zinc-50 border border-zinc-100 hover:border-black transition-all overflow-hidden"
              >
                <div className="absolute top-0 right-0 p-6 opacity-0 group-hover:opacity-100 transition-opacity">
                  <Sparkles className="w-5 h-5 text-blue-600" />
                </div>
                <div className="flex items-center gap-2 mb-2">
                  <Globe className="w-3.5 h-3.5 text-zinc-400" />
                  <p className="text-[10px] text-blue-600 font-bold uppercase tracking-widest truncate">{design.url}</p>
                </div>
                <h3 className="text-3xl font-black tracking-tighter mb-8 uppercase line-clamp-1">{design.url.split('.')[0]}</h3>
                
                <div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-zinc-400 group-hover:text-black transition-colors">
                  View full design
                  <ArrowRight className="w-3.5 h-3.5" />
                </div>
              </Link>
            ))}
          </motion.div>
        ) : (
          <div className="text-center py-20 border-2 border-dashed border-zinc-100 rounded-[32px]">
            <p className="text-zinc-400 font-bold uppercase tracking-widest text-xs">No designs archived yet.</p>
            <Link to="/" className="mt-4 inline-block text-blue-600 font-black uppercase tracking-tighter text-2xl hover:scale-105 transition-transform">Analyze a URL →</Link>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}

